image:
  provisioner: puppet
  tester: inspec
  driver:
    default: vagrant
    packer:
      aws_region: us-west-2
      instance_type: m5.large
      # security_group_id:
      source_ami: ami-02d0ea44ae3fe9561
      # subnet_id:
      volume_size: 20
      # vpc_id:
    vagrant:
      box: ubuntu/xenial64
      memory: 2048
