image:
  provisioner: puppet
  tester: inspec
  driver:
    default: vagrant
    packer:
      aws_region: us-west-2
      instance_type: m5.large
      # security_group_id:
      source_ami: ami-0d1cd67c26f5fca19
      # subnet_id:
      volume_size: 20
      # vpc_id:
    vagrant:
      box: ubuntu/bionic64
      memory: 2048
